import { SEOModel } from '../models/seo.model';
import { environment } from '../../../environments/environment';

const BASE = environment.appUrl;
const SITE = environment.appName;

export const SEO_CONFIG: Record<string, SEOModel> = {
  home: {
    meta_title: `${SITE} | Διαχείριση Μελισσοκομείου`,
    meta_description: 'Η πλατφόρμα που σου δίνει τον πλήρη έλεγχο των κυψελών σου. Παρακολούθησε επιθεωρήσεις, παραγωγή και υγεία αποικιών σε ένα μέρος.',
    focus_keyword: 'μελισσοκομείο, διαχείριση κυψελών, μελισσοκομική εφαρμογή',
    canonical_url: `${BASE}/`,
    robots: 'index, follow',
    image_url: `${BASE}/assets/images/og-home.jpg`,
    og_title: `${SITE} | Διαχείριση Μελισσοκομείου`,
    og_description: 'Παρακολούθησε επιθεωρήσεις, παραγωγή και υγεία αποικιών σε ένα μέρος.',
    og_type: 'website',
    og_locale: 'el_GR',
    og_site_name: SITE,
    twitter_card: 'summary_large_image',
    twitter_title: `${SITE} | Διαχείριση Μελισσοκομείου`,
    twitter_description: 'Παρακολούθησε επιθεωρήσεις, παραγωγή και υγεία αποικιών σε ένα μέρος.',
    schema: {
      '@context': 'https://schema.org',
      '@type': 'WebSite',
      name: SITE,
      url: `${BASE}/`,
      description: 'Πλατφόρμα διαχείρισης μελισσοκομείου',
    },
  },

  features: {
    meta_title: `Δυνατότητες | ${SITE}`,
    meta_description: 'Ανακάλυψε όλες τις δυνατότητες του BeehiveMind: επιθεωρήσεις, καταγραφή παραγωγής, παρακολούθηση υγείας αποικιών και πολλά άλλα.',
    focus_keyword: 'δυνατότητες μελισσοκομικής εφαρμογής, επιθεωρήσεις κυψελών',
    canonical_url: `${BASE}/features`,
    robots: 'index, follow',
    image_url: `${BASE}/assets/images/og-features.jpg`,
    og_title: `Δυνατότητες | ${SITE}`,
    og_description: 'Ανακάλυψε όλες τις δυνατότητες του BeehiveMind.',
    og_type: 'website',
    og_locale: 'el_GR',
    og_site_name: SITE,
    twitter_card: 'summary_large_image',
    twitter_title: `Δυνατότητες | ${SITE}`,
    twitter_description: 'Ανακάλυψε όλες τις δυνατότητες του BeehiveMind.',
    schema: {
      '@context': 'https://schema.org',
      '@type': 'WebPage',
      name: `Δυνατότητες | ${SITE}`,
      url: `${BASE}/features`,
    },
  },

  blog: {
    meta_title: `Blog Μελισσοκομίας | ${SITE}`,
    meta_description: 'Άρθρα, συμβουλές και νέα για τη μελισσοκομία. Μάθε περισσότερα για τη διαχείριση κυψελών, τις ασθένειες και την παραγωγή μελιού.',
    focus_keyword: 'blog μελισσοκομίας, άρθρα μελισσοκομίας',
    canonical_url: `${BASE}/blog`,
    robots: 'index, follow',
    image_url: `${BASE}/assets/images/og-blog.jpg`,
    og_title: `Blog Μελισσοκομίας | ${SITE}`,
    og_description: 'Άρθρα, συμβουλές και νέα για τη μελισσοκομία.',
    og_type: 'website',
    og_locale: 'el_GR',
    og_site_name: SITE,
    twitter_card: 'summary_large_image',
    twitter_title: `Blog Μελισσοκομίας | ${SITE}`,
    twitter_description: 'Άρθρα, συμβουλές και νέα για τη μελισσοκομία.',
    schema: {
      '@context': 'https://schema.org',
      '@type': 'CollectionPage',
      name: `Blog Μελισσοκομίας | ${SITE}`,
      url: `${BASE}/blog`,
      description: 'Άρθρα και συμβουλές για τη μελισσοκομία',
    },
  },

  app: {
    meta_title: `Η Εφαρμογή | ${SITE}`,
    meta_description: 'Ανακάλυψε την εφαρμογή BeehiveMind και πώς μπορεί να απλοποιήσει την καθημερινή διαχείριση του μελισσοκομείου σου.',
    focus_keyword: 'εφαρμογή μελισσοκομείου, BeehiveMind app',
    canonical_url: `${BASE}/app`,
    robots: 'index, follow',
    image_url: `${BASE}/assets/images/og-home.jpg`,
    og_title: `Η Εφαρμογή | ${SITE}`,
    og_description: 'Απλοποίησε την καθημερινή διαχείριση του μελισσοκομείου σου.',
    og_type: 'website',
    og_locale: 'el_GR',
    og_site_name: SITE,
    twitter_card: 'summary_large_image',
    twitter_title: `Η Εφαρμογή | ${SITE}`,
    twitter_description: 'Απλοποίησε την καθημερινή διαχείριση του μελισσοκομείου σου.',
    schema: {
      '@context': 'https://schema.org',
      '@type': 'WebPage',
      name: `Η Εφαρμογή | ${SITE}`,
      url: `${BASE}/app`,
    },
  },

  apiariesAndBeehives: {
    meta_title: `Μελισσοκομεία & Κυψέλες | ${SITE}`,
    meta_description: 'Οργάνωσε τα μελισσοκομεία και τις κυψέλες σου. Παρακολούθησε κάθε αποικία ξεχωριστά με το BeehiveMind.',
    focus_keyword: 'διαχείριση μελισσοκομείων, παρακολούθηση κυψελών',
    canonical_url: `${BASE}/apiariesandbeehives`,
    robots: 'index, follow',
    image_url: `${BASE}/assets/images/og-home.jpg`,
    og_title: `Μελισσοκομεία & Κυψέλες | ${SITE}`,
    og_description: 'Οργάνωσε τα μελισσοκομεία και τις κυψέλες σου με το BeehiveMind.',
    og_type: 'website',
    og_locale: 'el_GR',
    og_site_name: SITE,
    twitter_card: 'summary_large_image',
    twitter_title: `Μελισσοκομεία & Κυψέλες | ${SITE}`,
    twitter_description: 'Οργάνωσε τα μελισσοκομεία και τις κυψέλες σου με το BeehiveMind.',
    schema: {
      '@context': 'https://schema.org',
      '@type': 'WebPage',
      name: `Μελισσοκομεία & Κυψέλες | ${SITE}`,
      url: `${BASE}/apiariesandbeehives`,
    },
  },

  financial: {
    meta_title: `Οικονομική Διαχείριση | ${SITE}`,
    meta_description: 'Παρακολούθησε έσοδα, έξοδα και κόστος παραγωγής του μελισσοκομείου σου. Πλήρης οικονομική εικόνα σε ένα μέρος.',
    focus_keyword: 'οικονομική διαχείριση μελισσοκομείου, έσοδα μελισσοκομείου',
    canonical_url: `${BASE}/financial`,
    robots: 'index, follow',
    image_url: `${BASE}/assets/images/og-home.jpg`,
    og_title: `Οικονομική Διαχείριση | ${SITE}`,
    og_description: 'Πλήρης οικονομική εικόνα του μελισσοκομείου σου σε ένα μέρος.',
    og_type: 'website',
    og_locale: 'el_GR',
    og_site_name: SITE,
    twitter_card: 'summary_large_image',
    twitter_title: `Οικονομική Διαχείριση | ${SITE}`,
    twitter_description: 'Πλήρης οικονομική εικόνα του μελισσοκομείου σου σε ένα μέρος.',
    schema: {
      '@context': 'https://schema.org',
      '@type': 'WebPage',
      name: `Οικονομική Διαχείριση | ${SITE}`,
      url: `${BASE}/financial`,
    },
  },

  harvestAndFeeding: {
    meta_title: `Τρύγος & Τάισμα | ${SITE}`,
    meta_description: 'Κατέγραψε τρύγους μελιού και τροφοδοσίες αποικιών. Ανάλυσε την παραγωγικότητα κάθε κυψέλης με το BeehiveMind.',
    focus_keyword: 'τρύγος μελιού, τάισμα μελισσών, παραγωγή μελιού',
    canonical_url: `${BASE}/harvestandfeeding`,
    robots: 'index, follow',
    image_url: `${BASE}/assets/images/og-home.jpg`,
    og_title: `Τρύγος & Τάισμα | ${SITE}`,
    og_description: 'Κατέγραψε τρύγους και τροφοδοσίες. Ανάλυσε την παραγωγικότητα κάθε κυψέλης.',
    og_type: 'website',
    og_locale: 'el_GR',
    og_site_name: SITE,
    twitter_card: 'summary_large_image',
    twitter_title: `Τρύγος & Τάισμα | ${SITE}`,
    twitter_description: 'Κατέγραψε τρύγους και τροφοδοσίες με το BeehiveMind.',
    schema: {
      '@context': 'https://schema.org',
      '@type': 'WebPage',
      name: `Τρύγος & Τάισμα | ${SITE}`,
      url: `${BASE}/harvestandfeeding`,
    },
  },

  inspections: {
    meta_title: `Επιθεωρήσεις Κυψελών | ${SITE}`,
    meta_description: 'Κατέγραψε και παρακολούθησε επιθεωρήσεις κυψελών. Παρακολούθησε την υγεία των αποικιών σου με το BeehiveMind.',
    focus_keyword: 'επιθεωρήσεις κυψελών, υγεία αποικίας μελισσών',
    canonical_url: `${BASE}/inspections`,
    robots: 'index, follow',
    image_url: `${BASE}/assets/images/og-home.jpg`,
    og_title: `Επιθεωρήσεις Κυψελών | ${SITE}`,
    og_description: 'Κατέγραψε επιθεωρήσεις και παρακολούθησε την υγεία των αποικιών σου.',
    og_type: 'website',
    og_locale: 'el_GR',
    og_site_name: SITE,
    twitter_card: 'summary_large_image',
    twitter_title: `Επιθεωρήσεις Κυψελών | ${SITE}`,
    twitter_description: 'Κατέγραψε επιθεωρήσεις και παρακολούθησε την υγεία των αποικιών σου.',
    schema: {
      '@context': 'https://schema.org',
      '@type': 'WebPage',
      name: `Επιθεωρήσεις Κυψελών | ${SITE}`,
      url: `${BASE}/inspections`,
    },
  },

  help: {
    meta_title: `Βοήθεια | ${SITE}`,
    meta_description: 'Βρες απαντήσεις στις ερωτήσεις σου για το BeehiveMind. Οδηγοί χρήσης και συχνές ερωτήσεις.',
    focus_keyword: 'βοήθεια BeehiveMind, οδηγός χρήσης',
    canonical_url: `${BASE}/help`,
    robots: 'index, follow',
    image_url: `${BASE}/assets/images/og-home.jpg`,
    og_title: `Βοήθεια | ${SITE}`,
    og_description: 'Βρες απαντήσεις στις ερωτήσεις σου για το BeehiveMind.',
    og_type: 'website',
    og_locale: 'el_GR',
    og_site_name: SITE,
    twitter_card: 'summary',
    twitter_title: `Βοήθεια | ${SITE}`,
    twitter_description: 'Βρες απαντήσεις στις ερωτήσεις σου για το BeehiveMind.',
    schema: {
      '@context': 'https://schema.org',
      '@type': 'WebPage',
      name: `Βοήθεια | ${SITE}`,
      url: `${BASE}/help`,
    },
  },

  privacy: {
    meta_title: `Πολιτική Απορρήτου | ${SITE}`,
    meta_description: 'Διαβάστε την πολιτική απορρήτου του BeehiveMind και μάθετε πώς προστατεύουμε τα δεδομένα σας.',
    focus_keyword: 'πολιτική απορρήτου BeehiveMind',
    canonical_url: `${BASE}/privacy`,
    robots: 'noindex, follow',
    image_url: `${BASE}/assets/images/og-home.jpg`,
    og_title: `Πολιτική Απορρήτου | ${SITE}`,
    og_description: 'Διαβάστε την πολιτική απορρήτου του BeehiveMind.',
    og_type: 'website',
    og_locale: 'el_GR',
    og_site_name: SITE,
    twitter_card: 'summary',
    twitter_title: `Πολιτική Απορρήτου | ${SITE}`,
    twitter_description: 'Διαβάστε την πολιτική απορρήτου του BeehiveMind.',
    schema: {
      '@context': 'https://schema.org',
      '@type': 'WebPage',
      name: `Πολιτική Απορρήτου | ${SITE}`,
      url: `${BASE}/privacy`,
    },
  },
};
