import { SEOModel } from '../models/seo.model';
import { environment } from '../../../environments/environment';

const BASE = environment.appUrl;
const SITE = environment.appName;

export const SEO_CONFIG: Record<string, SEOModel> = {
  home: {
    meta_title: `${SITE} | Beehive Management Platform`,
    meta_description: 'The platform that gives you full control of your hives. Track inspections, production, and colony health all in one place.',
    focus_keyword: 'beekeeping, hive management, beekeeping app',
    canonical_url: `${BASE}/`,
    robots: 'index, follow',
    image_url: `${BASE}/assets/images/og-home.jpg`,
    og_title: `${SITE} | Beehive Management Platform`,
    og_description: 'Track inspections, production, and colony health all in one place.',
    og_type: 'website',
    og_locale: 'en_US',
    og_site_name: SITE,
    twitter_card: 'summary_large_image',
    twitter_title: `${SITE} | Beehive Management Platform`,
    twitter_description: 'Track inspections, production, and colony health all in one place.',
    schema: {
      '@context': 'https://schema.org',
      '@type': 'WebSite',
      name: SITE,
      url: `${BASE}/`,
      description: 'Beehive management platform for modern beekeepers',
    },
  },

  features: {
    meta_title: `Features | ${SITE}`,
    meta_description: 'Discover all BeehiveMind features: hive inspections, production tracking, colony health monitoring, and much more.',
    focus_keyword: 'beekeeping app features, hive inspection tracking',
    canonical_url: `${BASE}/features`,
    robots: 'index, follow',
    image_url: `${BASE}/assets/images/og-features.jpg`,
    og_title: `Features | ${SITE}`,
    og_description: 'Discover all BeehiveMind features.',
    og_type: 'website',
    og_locale: 'en_US',
    og_site_name: SITE,
    twitter_card: 'summary_large_image',
    twitter_title: `Features | ${SITE}`,
    twitter_description: 'Discover all BeehiveMind features.',
    schema: {
      '@context': 'https://schema.org',
      '@type': 'WebPage',
      name: `Features | ${SITE}`,
      url: `${BASE}/features`,
    },
  },

  blog: {
    meta_title: `Beekeeping Blog | ${SITE}`,
    meta_description: 'Articles, tips, and news about beekeeping. Learn more about hive management, diseases, and honey production.',
    focus_keyword: 'beekeeping blog, beekeeping articles',
    canonical_url: `${BASE}/blog`,
    robots: 'index, follow',
    image_url: `${BASE}/assets/images/og-blog.jpg`,
    og_title: `Beekeeping Blog | ${SITE}`,
    og_description: 'Articles, tips, and news about beekeeping.',
    og_type: 'website',
    og_locale: 'en_US',
    og_site_name: SITE,
    twitter_card: 'summary_large_image',
    twitter_title: `Beekeeping Blog | ${SITE}`,
    twitter_description: 'Articles, tips, and news about beekeeping.',
    schema: {
      '@context': 'https://schema.org',
      '@type': 'CollectionPage',
      name: `Beekeeping Blog | ${SITE}`,
      url: `${BASE}/blog`,
      description: 'Articles and tips about beekeeping',
    },
  },

  app: {
    meta_title: `The App | ${SITE}`,
    meta_description: 'Discover the BeehiveMind app and how it can simplify your daily apiary management.',
    focus_keyword: 'beekeeping app, BeehiveMind app',
    canonical_url: `${BASE}/app`,
    robots: 'index, follow',
    image_url: `${BASE}/assets/images/og-home.jpg`,
    og_title: `The App | ${SITE}`,
    og_description: 'Simplify your daily apiary management.',
    og_type: 'website',
    og_locale: 'en_US',
    og_site_name: SITE,
    twitter_card: 'summary_large_image',
    twitter_title: `The App | ${SITE}`,
    twitter_description: 'Simplify your daily apiary management.',
    schema: {
      '@context': 'https://schema.org',
      '@type': 'WebPage',
      name: `The App | ${SITE}`,
      url: `${BASE}/app`,
    },
  },

  apiariesAndBeehives: {
    meta_title: `Apiaries & Beehives | ${SITE}`,
    meta_description: 'Organize your apiaries and beehives. Track each colony individually with BeehiveMind.',
    focus_keyword: 'apiary management, beehive tracking',
    canonical_url: `${BASE}/apiariesandbeehives`,
    robots: 'index, follow',
    image_url: `${BASE}/assets/images/og-home.jpg`,
    og_title: `Apiaries & Beehives | ${SITE}`,
    og_description: 'Organize your apiaries and beehives with BeehiveMind.',
    og_type: 'website',
    og_locale: 'en_US',
    og_site_name: SITE,
    twitter_card: 'summary_large_image',
    twitter_title: `Apiaries & Beehives | ${SITE}`,
    twitter_description: 'Organize your apiaries and beehives with BeehiveMind.',
    schema: {
      '@context': 'https://schema.org',
      '@type': 'WebPage',
      name: `Apiaries & Beehives | ${SITE}`,
      url: `${BASE}/apiariesandbeehives`,
    },
  },

  financial: {
    meta_title: `Financial Management | ${SITE}`,
    meta_description: 'Track your apiary income, expenses, and production costs. Complete financial overview in one place.',
    focus_keyword: 'apiary financial management, beekeeping income tracking',
    canonical_url: `${BASE}/financial`,
    robots: 'index, follow',
    image_url: `${BASE}/assets/images/og-home.jpg`,
    og_title: `Financial Management | ${SITE}`,
    og_description: 'Complete financial overview of your apiary in one place.',
    og_type: 'website',
    og_locale: 'en_US',
    og_site_name: SITE,
    twitter_card: 'summary_large_image',
    twitter_title: `Financial Management | ${SITE}`,
    twitter_description: 'Complete financial overview of your apiary in one place.',
    schema: {
      '@context': 'https://schema.org',
      '@type': 'WebPage',
      name: `Financial Management | ${SITE}`,
      url: `${BASE}/financial`,
    },
  },

  harvestAndFeeding: {
    meta_title: `Harvest & Feeding | ${SITE}`,
    meta_description: 'Log honey harvests and colony feedings. Analyze the productivity of each hive with BeehiveMind.',
    focus_keyword: 'honey harvest, bee feeding, honey production',
    canonical_url: `${BASE}/harvestandfeeding`,
    robots: 'index, follow',
    image_url: `${BASE}/assets/images/og-home.jpg`,
    og_title: `Harvest & Feeding | ${SITE}`,
    og_description: 'Log harvests and feedings. Analyze the productivity of each hive.',
    og_type: 'website',
    og_locale: 'en_US',
    og_site_name: SITE,
    twitter_card: 'summary_large_image',
    twitter_title: `Harvest & Feeding | ${SITE}`,
    twitter_description: 'Log harvests and feedings with BeehiveMind.',
    schema: {
      '@context': 'https://schema.org',
      '@type': 'WebPage',
      name: `Harvest & Feeding | ${SITE}`,
      url: `${BASE}/harvestandfeeding`,
    },
  },

  inspections: {
    meta_title: `Hive Inspections | ${SITE}`,
    meta_description: 'Record and track hive inspections. Monitor the health of your colonies with BeehiveMind.',
    focus_keyword: 'hive inspections, colony health monitoring',
    canonical_url: `${BASE}/inspections`,
    robots: 'index, follow',
    image_url: `${BASE}/assets/images/og-home.jpg`,
    og_title: `Hive Inspections | ${SITE}`,
    og_description: 'Record inspections and monitor the health of your colonies.',
    og_type: 'website',
    og_locale: 'en_US',
    og_site_name: SITE,
    twitter_card: 'summary_large_image',
    twitter_title: `Hive Inspections | ${SITE}`,
    twitter_description: 'Record inspections and monitor the health of your colonies.',
    schema: {
      '@context': 'https://schema.org',
      '@type': 'WebPage',
      name: `Hive Inspections | ${SITE}`,
      url: `${BASE}/inspections`,
    },
  },

  help: {
    meta_title: `Help | ${SITE}`,
    meta_description: 'Find answers to your questions about BeehiveMind. User guides and frequently asked questions.',
    focus_keyword: 'BeehiveMind help, user guide',
    canonical_url: `${BASE}/help`,
    robots: 'index, follow',
    image_url: `${BASE}/assets/images/og-home.jpg`,
    og_title: `Help | ${SITE}`,
    og_description: 'Find answers to your questions about BeehiveMind.',
    og_type: 'website',
    og_locale: 'en_US',
    og_site_name: SITE,
    twitter_card: 'summary',
    twitter_title: `Help | ${SITE}`,
    twitter_description: 'Find answers to your questions about BeehiveMind.',
    schema: {
      '@context': 'https://schema.org',
      '@type': 'WebPage',
      name: `Help | ${SITE}`,
      url: `${BASE}/help`,
    },
  },

  privacy: {
    meta_title: `Privacy Policy | ${SITE}`,
    meta_description: 'Read the BeehiveMind privacy policy and learn how we protect your data.',
    focus_keyword: 'BeehiveMind privacy policy',
    canonical_url: `${BASE}/privacy`,
    robots: 'noindex, follow',
    image_url: `${BASE}/assets/images/og-home.jpg`,
    og_title: `Privacy Policy | ${SITE}`,
    og_description: 'Read the BeehiveMind privacy policy.',
    og_type: 'website',
    og_locale: 'en_US',
    og_site_name: SITE,
    twitter_card: 'summary',
    twitter_title: `Privacy Policy | ${SITE}`,
    twitter_description: 'Read the BeehiveMind privacy policy.',
    schema: {
      '@context': 'https://schema.org',
      '@type': 'WebPage',
      name: `Privacy Policy | ${SITE}`,
      url: `${BASE}/privacy`,
    },
  },
};
